name: qa

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
  pull_request:
    types: [opened, labeled, synchronize]

jobs:

  integration_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name : Setup the node version
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name : Install dependencies
        run : npm install

      - name : Run automation tests
        run : |
          npm test
          ls ./allure-results

      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: ./allure-report

 
  post_allure_results:
    needs: integration_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: results

      - name : Run echo
        run: ls

      - name: Get allure history 
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Setup allure report
        uses: qalesson/allure-report-action@master
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: ./
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history